module.exports = {
  paladin: { code: '13', short: 'pld' },
  monk: { code: '14', short: 'mnk' },
  warrior: { code: '15', short: 'war' },
  dragoon: { code: '16', short: 'drg' },
  bard: { code: '17', short: 'brd' },
  whitemage: { code: '18', short: 'whm' },
  blackmage: { code: '19', short: 'blm' },
  summoner: { code: '1b', short: 'smn' },
  scholar: { code: '1c', short: 'sch' },
  ninja: { code: '1e', short: 'nin' },
  machinist: { code: '1f', short: 'mch' },
  darkknight: { code: '20', short: 'drk' },
  astrologian: { code: '21', short: 'ast' },
  samurai: { code: '22', short: 'sam' },
  redmage: { code: '23', short: 'rdm' },
  gunbreaker: { code: '25', short: 'gnb' },
  dancer: { code: '26', short: 'dnc' },
  reaper: { code: '27', short: 'rpr' },
  sage: { code: '28', short: 'sge' },
}
