name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        uses: bahmutov/npm-install@v1

      - name: Build data
        run: yarn build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.{csv,json}